USE [master]
GO

/****** Object:  Database [Locadora]    Script Date: 15/07/2015 14:43:14 ******/
CREATE DATABASE [Locadora]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Locadora', FILENAME = N'C:\Users\Marcos\AppData\Local\Microsoft\VisualStudio\SSDT\Locadora\Locadora.mdf' , SIZE = 5312KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB )
 LOG ON 
( NAME = N'Locadora_log', FILENAME = N'C:\Users\Marcos\AppData\Local\Microsoft\VisualStudio\SSDT\Locadora\Locadora.ldf' , SIZE = 11200KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
GO

ALTER DATABASE [Locadora] SET COMPATIBILITY_LEVEL = 120
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Locadora].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Locadora] SET ANSI_NULL_DEFAULT ON 
GO

ALTER DATABASE [Locadora] SET ANSI_NULLS ON 
GO

ALTER DATABASE [Locadora] SET ANSI_PADDING ON 
GO

ALTER DATABASE [Locadora] SET ANSI_WARNINGS ON 
GO

ALTER DATABASE [Locadora] SET ARITHABORT ON 
GO

ALTER DATABASE [Locadora] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Locadora] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Locadora] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Locadora] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Locadora] SET CURSOR_DEFAULT  LOCAL 
GO

ALTER DATABASE [Locadora] SET CONCAT_NULL_YIELDS_NULL ON 
GO

ALTER DATABASE [Locadora] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Locadora] SET QUOTED_IDENTIFIER ON 
GO

ALTER DATABASE [Locadora] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Locadora] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Locadora] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Locadora] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Locadora] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Locadora] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Locadora] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Locadora] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Locadora] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Locadora] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Locadora] SET  MULTI_USER 
GO

ALTER DATABASE [Locadora] SET PAGE_VERIFY NONE  
GO

ALTER DATABASE [Locadora] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Locadora] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Locadora] SET TARGET_RECOVERY_TIME = 0 SECONDS 
GO

ALTER DATABASE [Locadora] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Locadora] SET  READ_WRITE 
GO

