//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locadora.Models.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Copia
    {
        public Copia()
        {
            this.Emprestimo = new HashSet<Emprestimo>();
        }
    
        public int IdCopia { get; set; }
        public Nullable<int> IdJogo { get; set; }
        public Nullable<int> IdFilme { get; set; }
        public bool Disponivel { get; set; }
    
        public virtual Filme Filme { get; set; }
        public virtual Jogo Jogo { get; set; }
        public virtual ICollection<Emprestimo> Emprestimo { get; set; }
    }
}
