//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locadora.Models.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Emprestimo
    {
        public int IdMatricula { get; set; }
        public int IdCopia { get; set; }
        public Nullable<System.DateTime> PeriodoInicial { get; set; }
        public Nullable<System.DateTime> PeriodoFinal { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        public virtual Copia Copia { get; set; }
    }
}
