//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locadora.Models.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Filme
    {
        public Filme()
        {
            this.Copia = new HashSet<Copia>();
        }
    
        public int IdFilme { get; set; }
        [Required(ErrorMessage="O título do filme é obrigatório")]
        public string Titulo { get; set; }
        [Required(ErrorMessage="O Ano de lançamento é obrigatório")]
        public string Ano { get; set; }
        public byte[] Capa { get; set; }
        public int IdGenero { get; set; }
    
        public virtual ICollection<Copia> Copia { get; set; }
        public virtual Genero Genero { get; set; }
    }
}
