//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locadora.Models.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Genero
    {
        public Genero()
        {
            this.Filme = new HashSet<Filme>();
            this.Jogo = new HashSet<Jogo>();
        }
    
        public int IdGenero { get; set; }
        public string NomeGenero { get; set; }
    
        public virtual ICollection<Filme> Filme { get; set; }
        public virtual ICollection<Jogo> Jogo { get; set; }
    }
}
