//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locadora.Models.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    
    public partial class Jogo
    {
        public Jogo()
        {
            this.Copia = new HashSet<Copia>();
            this.PlataformasJogo = new HashSet<PlataformasJogo>();
        }
    
        public int IdJogo { get; set; }

        [Required(ErrorMessage="O título do jogo é obrigatório")]
        public string Titulo { get; set; }

        [Required(ErrorMessage="O ano de lançamento é obrigatório")]
        public string Ano { get; set; }
        public byte[] Capa { get; set; }
        public int IdGenero { get; set; }
    
        public virtual ICollection<Copia> Copia { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual ICollection<PlataformasJogo> PlataformasJogo { get; set; }
    }
}
