//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locadora.Models.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class Jogo : Midia
    {
        public Jogo()
        {
            this.Copia = new HashSet<Copia>();
            this.PlataformasJogo = new HashSet<PlataformasJogo>();
        }
    
    
        public virtual ICollection<Copia> Copia { get; set; }
        public virtual Genero Genero { get; set; }
        public virtual ICollection<PlataformasJogo> PlataformasJogo { get; set; }
    }
}
