//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Locadora.Models.BusinessLayer
{
    using System;
    using System.Collections.Generic;
    
    public partial class PlataformasJogo
    {
        public int IdPlataforma { get; set; }
        public int IdJogo { get; set; }
        public int IdConsole { get; set; }
    
        public virtual Console Console { get; set; }
    }
}
